//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoi_Filippov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AgenstvoNedvezjEntities3 : DbContext
    {
        private static AgenstvoNedvezjEntities3 _context; public static AgenstvoNedvezjEntities3 GetContext() { if (_context == null) _context = new AgenstvoNedvezjEntities3(); return _context; }
        public AgenstvoNedvezjEntities3() : base("name=AgenstvoNedvezjEntities3") { }
        protected override void OnModelCreating(DbModelBuilder modelBuilder) { throw new UnintentionalCodeFirstException(); }

        public virtual DbSet<Nedvezj> Nedvezj { get; set; }
        public virtual DbSet<NedvezjType> NedvezjType { get; set; }
        public virtual DbSet<Prodavec> Prodavec { get; set; }
        public virtual DbSet<Rayon> Rayon { get; set; }
        public virtual DbSet<Sdelki> Sdelki { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
